### ISSUE TITLE
Erreur d'accès à la page /collection de l'API Features

### ISSUE THREAD

**Issue by bchartier** [bchartier/cicclo-ogcapi-agentconnect#2]
Erreur Django lors de l'accès à la page https://rec.onegeosuite.fr/geoserver/ogc/features/v1/collections/?f=application%2Fjson (en utilisant la liste déroulante au sommet de la page https://rec.onegeosuite.fr/geoserver/ogc/features/v1/collections).

Par contre, l'URL suivante fonctionne :
https://rec.onegeosuite.fr/geoserver/ogc/features/v1/collections?f=application%2Fjson

**Comment by sebastiendarocha** [comment]
c'est corrigé
