### ISSUE TITLE
Consulter les données avec l'API Features à partir d'une recherche dans le catalogue - OneGeo Suite

### ISSUE THREAD

**Issue by bchartier** [bchartier/cicclo-ogcapi-agentconnect#23]
Peut-on facilement ajouter une couche de données issue de l'API Features à partir d'une recherche effectuée dans le catalogue de OneGeo Suite ?

**Comment by mathildepommier** [comment]
Depuis la recherche (Explorer), il faut passer par la copie du lien dans l'onglet API (API FEATURES SERVICE) à recopier dans la visionneuse (Maps), il n'y a pas de lien direct.
Par contre, il est possible de visualiser les données depuis la recherche dans l'onglet Données. Par contre, on passe par WMS ou WFS dans cette onglet et non par API Features.
