### ISSUE TITLE
Accès aux liens de métadonnées dans la page /collections

### ISSUE THREAD

**Issue by bchartier** [bchartier/cicclo-ogcapi-agentconnect#24]
Aucun lien vers des métadonnées ne semble présent dans la page /collections dans l'instance de démo de geOrchestra de Camptocamp.
Est-ce que c'est parce qu'ils n'ont pas été renseignés ou parce que cela n'a pas été codé ?

**Comment by fvanderbiest** [comment]
Pour la couche https://demo.georchestra.org/geoserver/ogc/features/v1/collections/geor:georchestra_instances j'ai renseigné un lien vers les métadonnées : 
![image](https://github.com/user-attachments/assets/59564a38-b095-43e7-8827-cdb3ed9a9dda)

HTML :  https://demo.georchestra.org/datahub/dataset/6f7cbbdb-5899-495d-90db-fc26c9439284
XML : https://demo.georchestra.org/geonetwork/srv/api/records/6f7cbbdb-5899-495d-90db-fc26c9439284/formatters/xml

En effet je ne vois pas de lien apparaître pour cette couche dans https://demo.georchestra.org/geoserver/ogc/features/v1/collections/?f=application%2Fjson

**Comment by fvanderbiest** [comment]
It does work !
Il y a des liens spécifiques à renseigner, sur l'onglet "publication" de la couche, dans Geoserver.
![image](https://github.com/user-attachments/assets/2fef16ba-1801-4398-97db-dc99a282316e)

A partir de là, on retrouve ces liens dans les "capacités" de la couche, eg https://demo.georchestra.org/geoserver/ogc/features/v1/collections/geor:georchestra_instances?f=application%2Fjson
![image](https://github.com/user-attachments/assets/9134602d-6b22-48eb-8edd-c6cebd4e2afa)
